require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Newsletters::TemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # Newsletters::Template. As you add validations to Newsletters::Template, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Newsletters::TemplatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all newsletters_templates as @newsletters_templates" do
      template = Newsletters::Template.create! valid_attributes
      get :index, {}, valid_session
      assigns(:newsletters_templates).should eq([template])
    end
  end

  describe "GET show" do
    it "assigns the requested newsletters_template as @newsletters_template" do
      template = Newsletters::Template.create! valid_attributes
      get :show, {:id => template.to_param}, valid_session
      assigns(:newsletters_template).should eq(template)
    end
  end

  describe "GET new" do
    it "assigns a new newsletters_template as @newsletters_template" do
      get :new, {}, valid_session
      assigns(:newsletters_template).should be_a_new(Newsletters::Template)
    end
  end

  describe "GET edit" do
    it "assigns the requested newsletters_template as @newsletters_template" do
      template = Newsletters::Template.create! valid_attributes
      get :edit, {:id => template.to_param}, valid_session
      assigns(:newsletters_template).should eq(template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Newsletters::Template" do
        expect {
          post :create, {:newsletters_template => valid_attributes}, valid_session
        }.to change(Newsletters::Template, :count).by(1)
      end

      it "assigns a newly created newsletters_template as @newsletters_template" do
        post :create, {:newsletters_template => valid_attributes}, valid_session
        assigns(:newsletters_template).should be_a(Newsletters::Template)
        assigns(:newsletters_template).should be_persisted
      end

      it "redirects to the created newsletters_template" do
        post :create, {:newsletters_template => valid_attributes}, valid_session
        response.should redirect_to(Newsletters::Template.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newsletters_template as @newsletters_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newsletters::Template.any_instance.stub(:save).and_return(false)
        post :create, {:newsletters_template => { "name" => "invalid value" }}, valid_session
        assigns(:newsletters_template).should be_a_new(Newsletters::Template)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newsletters::Template.any_instance.stub(:save).and_return(false)
        post :create, {:newsletters_template => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newsletters_template" do
        template = Newsletters::Template.create! valid_attributes
        # Assuming there are no other newsletters_templates in the database, this
        # specifies that the Newsletters::Template created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Newsletters::Template.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => template.to_param, :newsletters_template => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested newsletters_template as @newsletters_template" do
        template = Newsletters::Template.create! valid_attributes
        put :update, {:id => template.to_param, :newsletters_template => valid_attributes}, valid_session
        assigns(:newsletters_template).should eq(template)
      end

      it "redirects to the newsletters_template" do
        template = Newsletters::Template.create! valid_attributes
        put :update, {:id => template.to_param, :newsletters_template => valid_attributes}, valid_session
        response.should redirect_to(template)
      end
    end

    describe "with invalid params" do
      it "assigns the newsletters_template as @newsletters_template" do
        template = Newsletters::Template.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newsletters::Template.any_instance.stub(:save).and_return(false)
        put :update, {:id => template.to_param, :newsletters_template => { "name" => "invalid value" }}, valid_session
        assigns(:newsletters_template).should eq(template)
      end

      it "re-renders the 'edit' template" do
        template = Newsletters::Template.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newsletters::Template.any_instance.stub(:save).and_return(false)
        put :update, {:id => template.to_param, :newsletters_template => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newsletters_template" do
      template = Newsletters::Template.create! valid_attributes
      expect {
        delete :destroy, {:id => template.to_param}, valid_session
      }.to change(Newsletters::Template, :count).by(-1)
    end

    it "redirects to the newsletters_templates list" do
      template = Newsletters::Template.create! valid_attributes
      delete :destroy, {:id => template.to_param}, valid_session
      response.should redirect_to(newsletters_templates_url)
    end
  end

end
